/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace.settings.index'
import { Route as WorkspaceSettingsEnvironmentsRouteImport } from './routes/_workspace.settings.environments'
import { Route as WorkspaceSettingsConnectionsRouteImport } from './routes/_workspace.settings.connections'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSettingsRoute,
} as any)
const WorkspaceSettingsEnvironmentsRoute =
  WorkspaceSettingsEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => WorkspaceSettingsRoute,
  } as any)
const WorkspaceSettingsConnectionsRoute =
  WorkspaceSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => WorkspaceSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/settings': typeof WorkspaceSettingsRouteWithChildren
  '/settings/connections': typeof WorkspaceSettingsConnectionsRoute
  '/settings/environments': typeof WorkspaceSettingsEnvironmentsRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkspaceIndexRoute
  '/settings/connections': typeof WorkspaceSettingsConnectionsRoute
  '/settings/environments': typeof WorkspaceSettingsEnvironmentsRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/settings': typeof WorkspaceSettingsRouteWithChildren
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/settings/connections': typeof WorkspaceSettingsConnectionsRoute
  '/_workspace/settings/environments': typeof WorkspaceSettingsEnvironmentsRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/connections'
    | '/settings/environments'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings/connections' | '/settings/environments' | '/settings'
  id:
    | '__root__'
    | '/_workspace'
    | '/_workspace/settings'
    | '/_workspace/'
    | '/_workspace/settings/connections'
    | '/_workspace/settings/environments'
    | '/_workspace/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsRoute
    }
    '/_workspace/settings/environments': {
      id: '/_workspace/settings/environments'
      path: '/environments'
      fullPath: '/settings/environments'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsRouteImport
      parentRoute: typeof WorkspaceSettingsRoute
    }
    '/_workspace/settings/connections': {
      id: '/_workspace/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof WorkspaceSettingsConnectionsRouteImport
      parentRoute: typeof WorkspaceSettingsRoute
    }
  }
}

interface WorkspaceSettingsRouteChildren {
  WorkspaceSettingsConnectionsRoute: typeof WorkspaceSettingsConnectionsRoute
  WorkspaceSettingsEnvironmentsRoute: typeof WorkspaceSettingsEnvironmentsRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
}

const WorkspaceSettingsRouteChildren: WorkspaceSettingsRouteChildren = {
  WorkspaceSettingsConnectionsRoute: WorkspaceSettingsConnectionsRoute,
  WorkspaceSettingsEnvironmentsRoute: WorkspaceSettingsEnvironmentsRoute,
  WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
}

const WorkspaceSettingsRouteWithChildren =
  WorkspaceSettingsRoute._addFileChildren(WorkspaceSettingsRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSettingsRoute: WorkspaceSettingsRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
