/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsEnvironmentsRouteImport } from './routes/settings/environments'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEnvironmentsRoute = SettingsEnvironmentsRouteImport.update({
  id: '/settings/environments',
  path: '/settings/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/connections'
    | '/settings/environments'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings/connections' | '/settings/environments' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/settings/connections'
    | '/settings/environments'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsEnvironmentsRoute: typeof SettingsEnvironmentsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/environments': {
      id: '/settings/environments'
      path: '/settings/environments'
      fullPath: '/settings/environments'
      preLoaderRoute: typeof SettingsEnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsEnvironmentsRoute: SettingsEnvironmentsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
