/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding.success'
import { Route as OnboardingImportRouteImport } from './routes/onboarding.import'
import { Route as OnboardingConnectionRouteImport } from './routes/onboarding.connection'
import { Route as WorkspaceSettingsRouteRouteImport } from './routes/_workspace/settings/route'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/_workspace/settings/index'
import { Route as WorkspaceSettingsEnvironmentsRouteImport } from './routes/_workspace/settings/environments'
import { Route as WorkspaceSettingsConnectionsRouteImport } from './routes/_workspace/settings/connections'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingImportRoute = OnboardingImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingConnectionRoute = OnboardingConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => OnboardingRoute,
} as any)
const WorkspaceSettingsRouteRoute = WorkspaceSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSettingsRouteRoute,
} as any)
const WorkspaceSettingsEnvironmentsRoute =
  WorkspaceSettingsEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)
const WorkspaceSettingsConnectionsRoute =
  WorkspaceSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => WorkspaceSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/onboarding/connection': typeof OnboardingConnectionRoute
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/settings/connections': typeof WorkspaceSettingsConnectionsRoute
  '/settings/environments': typeof WorkspaceSettingsEnvironmentsRoute
  '/settings/': typeof WorkspaceSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRouteWithChildren
  '/onboarding/connection': typeof OnboardingConnectionRoute
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/': typeof WorkspaceIndexRoute
  '/settings/connections': typeof WorkspaceSettingsConnectionsRoute
  '/settings/environments': typeof WorkspaceSettingsEnvironmentsRoute
  '/settings': typeof WorkspaceSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_workspace/settings': typeof WorkspaceSettingsRouteRouteWithChildren
  '/onboarding/connection': typeof OnboardingConnectionRoute
  '/onboarding/import': typeof OnboardingImportRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/settings/connections': typeof WorkspaceSettingsConnectionsRoute
  '/_workspace/settings/environments': typeof WorkspaceSettingsEnvironmentsRoute
  '/_workspace/settings/': typeof WorkspaceSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/settings'
    | '/onboarding/connection'
    | '/onboarding/import'
    | '/onboarding/success'
    | '/settings/connections'
    | '/settings/environments'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/onboarding/connection'
    | '/onboarding/import'
    | '/onboarding/success'
    | '/'
    | '/settings/connections'
    | '/settings/environments'
    | '/settings'
  id:
    | '__root__'
    | '/_workspace'
    | '/onboarding'
    | '/_workspace/settings'
    | '/onboarding/connection'
    | '/onboarding/import'
    | '/onboarding/success'
    | '/_workspace/'
    | '/_workspace/settings/connections'
    | '/_workspace/settings/environments'
    | '/_workspace/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/import': {
      id: '/onboarding/import'
      path: '/import'
      fullPath: '/onboarding/import'
      preLoaderRoute: typeof OnboardingImportRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/connection': {
      id: '/onboarding/connection'
      path: '/connection'
      fullPath: '/onboarding/connection'
      preLoaderRoute: typeof OnboardingConnectionRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings/': {
      id: '/_workspace/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/environments': {
      id: '/_workspace/settings/environments'
      path: '/environments'
      fullPath: '/settings/environments'
      preLoaderRoute: typeof WorkspaceSettingsEnvironmentsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
    '/_workspace/settings/connections': {
      id: '/_workspace/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof WorkspaceSettingsConnectionsRouteImport
      parentRoute: typeof WorkspaceSettingsRouteRoute
    }
  }
}

interface WorkspaceSettingsRouteRouteChildren {
  WorkspaceSettingsConnectionsRoute: typeof WorkspaceSettingsConnectionsRoute
  WorkspaceSettingsEnvironmentsRoute: typeof WorkspaceSettingsEnvironmentsRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
}

const WorkspaceSettingsRouteRouteChildren: WorkspaceSettingsRouteRouteChildren =
  {
    WorkspaceSettingsConnectionsRoute: WorkspaceSettingsConnectionsRoute,
    WorkspaceSettingsEnvironmentsRoute: WorkspaceSettingsEnvironmentsRoute,
    WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
  }

const WorkspaceSettingsRouteRouteWithChildren =
  WorkspaceSettingsRouteRoute._addFileChildren(
    WorkspaceSettingsRouteRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceSettingsRouteRoute: typeof WorkspaceSettingsRouteRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSettingsRouteRoute: WorkspaceSettingsRouteRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingConnectionRoute: typeof OnboardingConnectionRoute
  OnboardingImportRoute: typeof OnboardingImportRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingConnectionRoute: OnboardingConnectionRoute,
  OnboardingImportRoute: OnboardingImportRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
